### ISSUE TITLE
Death Glitch

### ISSUE THREAD

**Issue by StealthParad0x** [Joexv/TowerDiver#2]
I killed Death and it said i got a class but when i checked there was only the ones i had King,Warrior,Archer, and mage.   P.S I already had the king before this

**Comment by Joexv** [comment]
Okay I've found the bugged that caused that, and I've got an update for it. The update for it should be published within a week or so, but if you would like I can add you to our TestFlight beta and get you the update right away. Send me an email if you would like to do that
manmadeofgouda@gmail.com
